/* ============================================================
   SCHEMA / DATA DICTIONARY — single source of truth  (Stage 2b)
   ============================================================
   A programmatic data dictionary for every Firestore collection. This is the
   machine-readable companion to /docs/DATA_DICTIONARY.md: future features and
   validators can ask "what fields does an order have / who owns this field /
   is it required" without hunting through module code.

   Each field entry:
     type      : 'string' | 'number' | 'date' | 'bool' | 'array' | 'map'
     owner     : 'ERP' | 'Phoenix'
     editable  : true | false | 'erp-seed'  (erp-seed = ERP seeds, Phoenix may edit)
     required  : true | false
     ui        : short note on where it appears
     meaning   : human description

   This object is intentionally declarative and side-effect free. It does NOT
   enforce anything by itself — validators.js (Stage 2c) reads from it.

   NOTE (Path B): exposed as window.PXSchema; a later pass can convert to a real
   ES export without changing consumers. */
(function () {
  const F = (meaning, type, owner, editable, required, ui) =>
    ({ meaning, type, owner, editable, required, ui });

  const schema = {
    orders: {
      orderId:        F('Order number (FPO/LPO); = ERP doc no. for ERP orders', 'string', 'ERP', 'erp-seed', true, 'list, detail, form, reports'),
      entity:         F('Owning company: Phoenix / Seychelles Breweries / Edena', 'string', 'Phoenix', true, true, 'form, badge, all lists/dashboard/reports'),
      orderType:      F('foreign (FPO) or local (LPO). For Business Central imports, blank local-currency code or the entity local currency code itself imports as local: SCR for Seychelles Breweries, EUR for Edena.', 'string', 'Phoenix', true, true, 'form, split views, ERP import'),
      supplier:       F('Supplier name', 'string', 'ERP', 'erp-seed', true, 'list, detail, form'),
      supplierId:     F('Stable Phoenix supplier-master document id; preserves supplier linkage if the display name changes', 'string', 'Phoenix', false, false, 'detail, import/reconciliation'),
      supplierMatchMethod: F('How the supplier master was linked: vendorNo / name / alias / unmatched / manual', 'string', 'Phoenix', false, false, 'detail, import/reconciliation'),
      supplierOverrideReason: F('Authorised reason for using a blocked supplier', 'string', 'Phoenix', false, false, 'order audit'),
      supplierOverrideBy: F('Officer code that authorised a blocked-supplier override', 'string', 'Phoenix', false, false, 'order audit'),
      supplierOverrideAt: F('Timestamp of blocked-supplier override', 'date', 'Phoenix', false, false, 'order audit'),
      currency:       F('Order currency', 'string', 'ERP', 'erp-seed', true, 'list, detail, form'),
      amount:         F('Order total (master value)', 'number', 'ERP', 'erp-seed', true, 'list, detail, form'),
      dateOfOrder:    F('Order/PO date', 'date', 'ERP', 'erp-seed', false, 'detail, form, dashboard'),
      description:    F('Order description', 'string', 'ERP', 'erp-seed', false, 'list, detail, form'),
      category:       F('Procurement category (drives function)', 'string', 'ERP', 'erp-seed', false, 'form, filters'),
      function:       F('technical / indirect / supplychain (derived from category)', 'string', 'Phoenix', true, false, 'split views, filters'),
      noShipment:     F('No shipment required by default (service, works, licence, subscription, etc.). Local tangible orders normally receive directly by order-level GRNs; an exceptional local shipment may still be created when logistics is involved. Foreign tangible orders normally require shipment follow-up.', 'bool', 'Phoenix', true, false, 'form, detail, hides shipment request for service/works; receipt/OTIF uses actual GRN/shipment evidence'),
      stagedPayment:  F('Local order paid in stages (enables milestones)', 'bool', 'Phoenix', true, false, 'local order form, milestones'),
      paymentTerms:   F('Payment terms (drives milestone schedule)', 'string', 'ERP', 'erp-seed', false, 'form, milestones'),
      incoterm:       F('Foreign-order Incoterm, e.g. EXW / FOB / CIF; Phoenix-managed until supplied by ERP', 'string', 'Phoenix', true, false, 'foreign order form, detail, Data Quality'),
      plannedShipmentMode: F('Planned foreign-order transport mode before a shipment is created', 'string', 'Phoenix', true, false, 'foreign order form, Data Quality'),
      plannedFreightForwarder: F('Planned freight forwarder before a shipment is created', 'string', 'Phoenix', true, false, 'foreign order form, Data Quality'),
      shipmentPlanNotes: F('Foreign-order shipment plan / booking notes', 'string', 'Phoenix', true, false, 'foreign order form, detail'),
      status:         F('Phoenix operational status', 'string', 'Phoenix', true, false, 'list, detail, dashboard, My Work'),
      milestones:     F('Milestone payment schedule (array of {label,percent,amount,...})', 'array', 'Phoenix', true, false, 'detail, payments, forecast'),
      notes:          F('Free-text notes', 'string', 'Phoenix', true, false, 'detail, form'),
      orderAcknowledgedDate: F('Date supplier acknowledged', 'date', 'Phoenix', true, false, 'form, timeline'),
      orderReadyDate: F('Date goods ready', 'date', 'Phoenix', true, false, 'form, timeline'),
      orderSentToSupplierDate: F('Date PO sent to supplier', 'date', 'Phoenix', true, false, 'form, detail — all functions'),
      supplierPromisedDate: F('Supplier original promised delivery / readiness commitment date', 'date', 'Phoenix', true, false, 'order form, detail, My Work, dashboard'),
      supplierRevisedPromisedDate: F('Latest revised supplier commitment date when the original promise changes', 'date', 'Phoenix', true, false, 'order form, detail, My Work, dashboard'),
      supplierPromiseRevisionCount: F('Number of times the supplier commitment date has been revised', 'number', 'Phoenix', true, false, 'order form, risk score, supplier performance'),
      supplierDelayReason: F('Supplier-stated delay reason or blocker for the current commitment', 'string', 'Phoenix', true, false, 'order form, detail, risk score'),
      lastSupplierFollowupDate: F('Date the purchasing officer last chased or received a meaningful supplier update', 'date', 'Phoenix', true, false, 'order form, My Work, ageing'),
      nextSupplierFollowupDate: F('Next planned supplier chase / expediting action date', 'date', 'Phoenix', true, false, 'order form, My Work, dashboard'),
      followupMethod: F('Preferred / last follow-up channel: email, phone, Teams, supplier portal, meeting, other', 'string', 'Phoenix', true, false, 'order form, detail'),
      followupFrequencyDays: F('Expected chase cadence in working days for this order', 'number', 'Phoenix', true, false, 'order form, risk score'),
      supplierReplySummary: F('Short summary of the supplier reply / latest commitment', 'string', 'Phoenix', true, false, 'order form, detail'),
      orderCriticality: F('Business criticality: low / normal / high / critical; influences follow-up risk score', 'string', 'Phoenix', true, false, 'order form, detail, dashboard'),
      escalationOwner: F('Officer or manager currently owning escalation for this order', 'string', 'Phoenix', true, false, 'order form, detail, My Work'),
      escalationDate: F('Date this order was escalated for management follow-up', 'date', 'Phoenix', true, false, 'order form, detail, reports'),
      escalationLevel: F('Escalation level for supplier/order follow-up', 'number', 'Phoenix', true, false, 'order form, detail, reports'),
      plannedDates:   F('Planned/commitment date per timeline milestone {milestoneKey: date} — Phoenix-set now, prepared to be ERP/supplier-sourced', 'object', 'Phoenix', true, false, 'Timeline tab (Order Detail), timeline editor'),
      actualDates:    F('Supplementary/override actual date per timeline milestone {milestoneKey: date} for milestones with no canonical field (e.g. departure, arrival)', 'object', 'Phoenix', true, false, 'Timeline tab (Order Detail), timeline editor'),
      quantity:       F('Legacy header quantity for historical orders; new Supply Chain quantities are held per item in supplyChainItems[]', 'number', 'Phoenix', true, false, 'legacy detail, list, shipment summary'),
      supplyChainItems: F('Supply Chain-only item rows: array of {id, detailedDescription, quantity}', 'array', 'Phoenix', true, false, 'Supply Chain order form, detail'),
      paymentApprovedBy: F('[Deprecated — approval now lives on the RFP] legacy value kept for old records', 'string', 'Phoenix', true, false, 'legacy'),
      requestedReceiptDate: F('Requested receipt date', 'date', 'Phoenix', true, false, 'form, forecast anchor, order lists'),
      iprNumber:      F('Created From IPR No. (ERP)', 'string', 'ERP', 'erp-seed', false, 'detail, order lists'),
      iprApprovedDate: F('IPR HOD approval date (ERP)', 'date', 'ERP', 'erp-seed', false, 'detail, list'),
      claimant:       F('Requested By / claimant (ERP)', 'string', 'ERP', 'erp-seed', false, 'detail, order lists'),
      isClosed:       F('Order closed flag', 'bool', 'Phoenix', true, false, 'lists, dashboard'),
      closedAt:       F('Date the order was closed', 'date', 'Phoenix', false, false, 'closed orders list'),
      amendments:     F('Inc.5a: array of {id,field,label,oldValue,newValue,reason,amendedBy,amendedAt} — logged on save when a tracked PO field changes', 'array', 'Phoenix', true, false, 'order detail amendment history'),
      claims:         F('Inc.5c: array of {id,type,amount,currency,status,raisedDate,resolvedDate,raisedBy,assignedTo,note} — supplier claims (quality/quantity/damage/late)', 'array', 'Phoenix', true, false, 'order detail claims tab'),
      lines:          F('ERP PO lines master (read-only). Array of {lineId, lineNo, itemNumber, description, orderedQty (alias quantity), uom, unitCost, lineAmount, cancelledQty, expectedDeliveryDate}', 'array', 'ERP', false, false, 'detail PO-lines tab'),
      receipts:       F('Phoenix GRN control events. Array of {receiptId, lineId optional, shipmentId optional, grnRef/grnNumber, grnDate, actualReceiptDate optional, receivedQty optional, status pending/partially received/fully received/cancelled, notes, recordedBy, recordedAt}. Order-level GRNs handle local orders and services/works; shipment-linked GRNs handle foreign shipments and exceptional local shipments. Delivery is not a separate layer.', 'array', 'Phoenix', true, false, 'Order Detail GRNs tab, Shipment Detail GRNs section, PO-lines tab'),
      lineTracking:   F('Phoenix per-line operational controls. Array of {lineId, closed, closureReason, exceptionApproved, notes, updatedBy, updatedAt}', 'array', 'Phoenix', true, false, 'detail PO-lines tab'),
      erpSource:      F('Manual / Navision / Business Central', 'string', 'ERP', false, false, 'badge'),
      erpCompany:     F('ERP company/database name, e.g. PHOENIX-NAV / SEYBREW-BC (source system instance)', 'string', 'ERP', false, false, 'detail, reconciliation'),
      erpEntityId:    F('ERP entity/company code — stable integration key, independent of PO number', 'string', 'ERP', false, false, 'reconciliation'),
      erpDocumentId:  F('ERP internal document id/GUID — stable key that survives renumbering (preferred match key)', 'string', 'ERP', false, false, 'reconciliation'),
      erpDocumentNo:  F('ERP document number as shown in the ERP (may differ from Phoenix orderId)', 'string', 'ERP', false, false, 'detail, reconciliation'),
      erpSyncStatus:  F('synced / pending / error', 'string', 'ERP', false, false, 'badge'),
      erpLastSyncedAt:F('Last ERP sync time', 'date', 'ERP', false, false, 'badge tooltip'),
      lastRefreshChanges:F('Key fields (Amount/Currency/Requested Receipt Date) changed by the most recent warehouse refresh, as {field,label,old,new}. Cleared each import — shows only the latest refresh. For officer review; warehouse value still applies.', 'array', 'Phoenix', false, false, 'ERP Reconciliation, order badge'),
      lastRefreshAt:F('Timestamp of the most recent warehouse refresh that touched this order.', 'date', 'Phoenix', false, false, 'ERP Reconciliation'),
      integrationLayer: F('Integration layer that last supplied ERP data: manual / excel-import / data-warehouse / api-sync', 'string', 'ERP', false, false, 'badge, reconciliation'),
      warehouseSource: F('Data Warehouse/staging source view, table, or manual feed name that supplied the latest ERP values', 'string', 'ERP', false, false, 'reconciliation, audit'),
      warehouseRecordId: F('Stable warehouse/staging row identifier, if supplied by the integration layer', 'string', 'ERP', false, false, 'reconciliation, audit'),
      warehouseBatchId: F('Warehouse load batch or manual import run id used for the latest refresh', 'string', 'ERP', false, false, 'reconciliation, import history'),
      warehouseExtractedAt: F('Timestamp when the ERP source data was extracted into the warehouse/staging layer', 'date', 'ERP', false, false, 'reconciliation'),
      warehouseLoadedAt: F('Timestamp when Phoenix received or loaded the warehouse/staging record', 'date', 'ERP', false, false, 'reconciliation'),
      warehouseHash: F('Optional warehouse row/version hash used to detect changed ERP records without comparing every field', 'string', 'ERP', false, false, 'reconciliation, future sync'),
      erpVendorNo:    F('ERP Buy-from Vendor No.', 'string', 'ERP', false, false, 'detail, ERP reconciliation'),
      erpVendorName:  F('ERP Buy-from Vendor Name (compared to supplier in reconciliation)', 'string', 'ERP', false, false, 'reconciliation (supplier mismatch)'),
      erpAmount:      F('ERP PO master amount (sum of line amounts on import)', 'number', 'ERP', false, false, 'reconciliation (amount mismatch)'),
      erpCurrency:    F('ERP currency code after local-currency interpretation for Business Central imports: blank becomes SCR for Seychelles Breweries or EUR for Edena', 'string', 'ERP', false, false, 'reconciliation (currency mismatch)'),
      erpPoStatus:    F('ERP PO lifecycle status (Open/Closed/Cancelled) — NEVER written into Phoenix status', 'string', 'ERP', false, false, 'reconciliation, badge'),
      erpHodId:       F('ERP HOD ID (drives Phoenix function classification on import)', 'string', 'ERP', false, false, 'import classification'),
      erpPurchasingMgrId: F('ERP Purchasing Manager ID (drives function classification on import)', 'string', 'ERP', false, false, 'import classification'),
      erpCreatedFromIpr: F('ERP Created From IPR No.', 'string', 'ERP', false, false, 'detail'),
      erpCreatedBy:   F('ERP Created By (Seychelles/Edena BC fallback when Purchaser Code is blank)', 'string', 'ERP', false, false, 'import classification'),
      erpPurchaserCode: F('Business Central Purchaser Code (primary Seychelles/Edena function classifier)', 'string', 'ERP', false, false, 'import classification, detail, reconciliation'),
      erpShipmentMethod: F('ERP Shipment Method Code, e.g. CIF (Seychelles BC)', 'string', 'ERP', false, false, 'detail'),
      amountInclVat:  F('PO amount including VAT (Seychelles/Edena BC; net amount is in Amount)', 'number', 'ERP', false, false, 'detail'),
      paymentDueDate: F('PO Due Date (payment due). From Business Central "Due Date" for Seychelles/Edena.', 'date', 'ERP', false, false, 'detail'),
      locationCode:   F('Business Central Location Code (Seychelles/Edena)', 'string', 'ERP', false, false, 'detail'),
      departmentCode: F('Business Central Department Code (Seychelles/Edena)', 'string', 'ERP', false, false, 'detail'),
      logisticStatus: F('Business Central Logistic Status (Seychelles/Edena)', 'string', 'ERP', false, false, 'detail'),
      amountReceivedNotInvoiced: F('Amount Received Not Invoiced (LCY) — value received but not yet invoiced (Seychelles/Edena BC; GRN/receipt tracking)', 'number', 'ERP', false, false, 'detail'),
      createdAt:      F('Created timestamp', 'date', 'Phoenix', false, false, 'audit'),
      createdBy:      F('Creator officer code', 'string', 'Phoenix', false, false, 'audit'),
      updatedAt:      F('Updated timestamp', 'date', 'Phoenix', false, false, 'audit'),
      updatedBy:      F('Updater officer code', 'string', 'Phoenix', false, false, 'audit')
    },

    shipments: {
      shipmentId:     F('orderId + shipment sequence (e.g. FPO12345 (S1), FPO12345 (S2))', 'string', 'Phoenix', true, true, 'list, detail, form'),
      orderId:        F('Linked order number', 'string', 'Phoenix', true, true, 'list, detail'),
      entity:         F('Owning company (inherited from order)', 'string', 'Phoenix', false, false, 'scopes lists'),
      supplier:       F('Supplier (from order)', 'string', 'Phoenix', true, false, 'list, detail'),
      stage:          F('requested / assigned / in_progress / completed', 'string', 'Phoenix', true, false, 'list, My Work'),
      status:         F('Shipping status', 'string', 'Phoenix', true, false, 'list, detail'),
      shipmentCoverage: F('Control scope only: full order / partial order / balance shipment / replacement shipment', 'string', 'Phoenix', true, false, 'shipment form, detail, list'),
      partialShipmentReason: F('Reason for partial, split, balance or replacement shipment without reproducing ERP PO lines', 'string', 'Phoenix', true, false, 'shipment form, detail'),
      movementSummary: F('Short free-text summary of what is moving; ERP remains the item-line source of truth', 'string', 'Phoenix', true, false, 'shipment form, detail, search'),
      sameMovement:    F('Yes/no control flag: multiple lots remain under same vessel/flight/logistics movement', 'string', 'Phoenix', true, false, 'shipment form, detail'),
      transportSplit:  F('Yes/no control flag: shipment is split by different transport mode/route and normally needs separate shipment records', 'string', 'Phoenix', true, false, 'shipment form, detail'),
      expectedCompleteAfterShipment: F('Yes/no control flag: order is expected to be complete after this shipment', 'string', 'Phoenix', true, false, 'shipment form, detail'),
      receiptResult:   F('Control result after warehouse/store receipt: fully received / partially received / short / missing / damaged', 'string', 'Phoenix', true, false, 'shipment form, detail, list'),
      followupAction:  F('Control action required from shipment exception: create next shipment / raise issue / close balance / await confirmation', 'string', 'Phoenix', true, false, 'shipment form, detail, list, My Work'),
      followupActionStatus: F('Processed-state marker for a shipment follow-up action; processed actions no longer appear in My Work', 'string', 'Phoenix', false, false, 'shipment detail, My Work'),
      followupActionProcessedAt: F('Timestamp when the shipment follow-up action was processed', 'date', 'Phoenix', false, false, 'audit, My Work'),
      followupActionProcessedBy: F('Officer code that processed the shipment follow-up action', 'string', 'Phoenix', false, false, 'audit, My Work'),
      followupActionProcessedByShipmentId: F('Shipment reference that processed a Create next shipment action', 'string', 'Phoenix', false, false, 'audit, My Work'),
      logisticOfficer:F('Assigned logistics officer', 'string', 'Phoenix', true, false, 'detail, My Work'),
      eta:            F('Estimated arrival', 'date', 'Phoenix', true, false, 'detail, My Work'),
      actualDepartureDate: F('Actual departure date / time recorded by logistics', 'date', 'Phoenix', true, false, 'shipment form, Data Quality'),
      actualArrivalDate: F('Actual arrival date at destination / port; use portArrivalDate for sea-container tracker', 'date', 'Phoenix', true, false, 'shipment form, Data Quality'),
      etaChangeHistory: F('Automatic ETA-change audit array: {previousEta,newEta,changedAt,changedBy}', 'array', 'Phoenix', false, false, 'shipment detail, Data Quality'),
      etd:            F('Estimated departure date', 'date', 'Phoenix', true, false, 'detail, journey'),
      requiredDocs:   F('Document-readiness checklist: array of {key,label,status(awaited/received/na),receivedDate,from,note}', 'array', 'Phoenix', true, false, 'shipment detail document readiness'),
      grnNumber:      F('Legacy/latest GRN number summary copied from linked order receipts[] for list/report compatibility; detailed GRN rows live on orders.receipts[]', 'string', 'Phoenix', true, false, 'detail, list summary'),
      grnDate:        F('Legacy/latest GRN date summary copied from linked order receipts[] for list/report compatibility. For timing, deliveryDate is preferred and GRN date is fallback.', 'date', 'Phoenix', true, false, 'detail, performance summary'),
      vesselFlight:   F('Vessel / flight reference', 'string', 'Phoenix', true, false, 'detail'),
      bookingDate:    F('Logistic / booking date (supply chain)', 'date', 'Phoenix', true, false, 'detail, form — foreign only'),
      shippingDocsDate: F('Shipping docs receipt/validation V/S FPO date (supply chain)', 'date', 'Phoenix', true, false, 'detail, form — foreign only'),
      invoiceToAccountsDate: F('Invoice sent to Accounts for costing date (supply chain)', 'date', 'Phoenix', true, false, 'detail, form — foreign only'),
      coaPostedDate:  F('COA posted date (supply chain)', 'date', 'Phoenix', true, false, 'detail, form — foreign only'),
      clearanceStatus: F('Clearance status — free text (supply chain)', 'string', 'Phoenix', true, false, 'detail, form — foreign only'),
      clearanceOwner: F('Officer accountable for customs / clearance follow-up', 'string', 'Phoenix', true, false, 'shipment form, Data Quality'),
      clearanceStartDate: F('Date customs / clearance processing started', 'date', 'Phoenix', true, false, 'shipment form, Data Quality'),
      customsReleaseDate: F('Date customs / broker released the cargo', 'date', 'Phoenix', true, false, 'shipment form, Data Quality'),
      deliveryDate: F('Date cargo was delivered to site / warehouse', 'date', 'Phoenix', true, false, 'shipment form, Data Quality'),
      containerCount: F('Number of containers (supply chain)', 'number', 'Phoenix', true, false, 'detail, form — foreign only'),
      portArrivalDate:       F('Inc.3: date vessel/container arrived at port of discharge', 'date', 'Phoenix', true, false, 'container tracker'),
      demurrageFreeDays:     F('Inc.3: free days before demurrage starts (from port arrival)', 'number', 'Phoenix', true, false, 'container tracker'),
      containerPickupDate:   F('Inc.3: date container picked up from port (demurrage stops, detention starts)', 'date', 'Phoenix', true, false, 'container tracker'),
      detentionFreeDays:     F('Inc.3: free days for detention before charges start (from pickup)', 'number', 'Phoenix', true, false, 'container tracker'),
      containerReturnDate:   F('Inc.3: date empty container returned to shipping line (detention stops)', 'date', 'Phoenix', true, false, 'container tracker'),
      demurrageRatePerDay:   F('Inc.3: demurrage charge per container per day (for cost projection)', 'number', 'Phoenix', true, false, 'container tracker'),
      detentionRatePerDay:   F('Inc.3: detention charge per container per day (for cost projection)', 'number', 'Phoenix', true, false, 'container tracker'),
      trackerCurrency:       F('Inc.3: currency for demurrage/detention rates', 'string', 'Phoenix', true, false, 'container tracker'),
      completed:      F('Completed flag', 'bool', 'Phoenix', true, false, 'list'),
      requestedBy:    F('Officer who requested', 'string', 'Phoenix', false, false, 'My Work'),
      mode:           F('Transport mode (SEA / AIR)', 'string', 'Phoenix', true, false, 'detail, TEPS'),
      invoiceValue:   F('TEPS: goods invoice value (foreign currency)', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      invoiceCurrency:F('TEPS: invoice currency', 'string', 'Phoenix', true, false, 'TEPS forecast'),
      exchangeRate:   F('TEPS: exchange rate to MUR', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      tepsFreight:    F('TEPS: freight cost in MUR', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      insuranceRate:  F('TEPS: insurance rate % (default 0.2)', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      vatRate:        F('TEPS: VAT rate % (default 15)', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      isAlcohol:      F('TEPS: alcoholic beverage (excise applies)', 'bool', 'Phoenix', true, false, 'TEPS forecast'),
      exciseDuties:   F('TEPS: Excise & Duties, manual from MRA (alcohol only)', 'number', 'Phoenix', true, false, 'TEPS forecast'),
      cfrValue:       F('TEPS computed: CFR = freight + invoice×rate', 'number', 'Phoenix', false, false, 'TEPS forecast'),
      tepsInsurance:  F('TEPS computed: insurance = CFR × rate%', 'number', 'Phoenix', false, false, 'TEPS forecast'),
      tepsVat:        F('TEPS computed: VAT = (CFR+insurance) × rate%', 'number', 'Phoenix', false, false, 'TEPS forecast'),
      totalProvision: F('TEPS computed: VAT + Excise & Duties', 'number', 'Phoenix', false, false, 'TEPS forecast, A/C export'),
      actualLandedCostMUR: F('Inc.2: actual total landed cost in MUR after clearance (entered once final duty/VAT/freight invoices received)', 'number', 'Phoenix', true, false, 'TEPS actual vs estimate, A/C export'),
      actualLandedCostDate: F('Inc.2: date actual landed cost was confirmed', 'date', 'Phoenix', true, false, 'TEPS actual vs estimate'),
      actualLandedCostNote: F('Inc.2: note on actual cost source (e.g. customs declaration ref, broker invoice no.)', 'string', 'Phoenix', true, false, 'TEPS actual vs estimate')
    },

    payment_requests: {
      rfpRef:         F('RFP reference (per-entity auto-number)', 'string', 'Phoenix', false, true, 'list, detail, form'),
      entity:         F('Owning company (inherited from order); drives RFP counter', 'string', 'Phoenix', false, false, 'scopes lists'),
      orderId:        F('Linked order', 'string', 'Phoenix', true, true, 'list, detail'),
      supplier:       F('Supplier', 'string', 'Phoenix', true, false, 'list, detail'),
      milestoneId:    F('Linked milestone id', 'string', 'Phoenix', true, false, 'detail, milestone sync'),
      amount:         F('Payment amount', 'number', 'Phoenix', true, true, 'list, detail, forecast'),
      currency:       F('Currency', 'string', 'Phoenix', true, false, 'list, detail'),
      dueDate:        F('Payment due date', 'date', 'Phoenix', true, true, 'list, My Work, forecast'),
      status:         F('draft / submitted / approved / paid / rejected', 'string', 'Phoenix', true, false, 'list, detail'),
      invoiceNumber:  F('Supplier invoice number', 'string', 'Phoenix', true, false, 'detail, My Work'),
      invoiceDate:    F('Supplier invoice date', 'date', 'Phoenix', true, false, 'payment form, Data Quality'),
      iblValueDate:   F('IBL value date (used as paid date)', 'date', 'Phoenix', true, false, 'detail'),
      paymentReference: F('Bank / payment transaction reference for a paid RFP', 'string', 'Phoenix', true, false, 'payment form, Data Quality'),
      requestDate:    F('RFP request date', 'date', 'Phoenix', true, false, 'detail'),
      paymentApproved: F('Request for payment approved', 'bool', 'Phoenix', true, false, 'form, detail, reflected on order'),
      paymentApprovedBy: F('Approved by (AB / MC)', 'string', 'Phoenix', true, false, 'form, detail'),
      paymentApprovedDate: F('Approval date', 'date', 'Phoenix', true, false, 'form, detail, reflected on order'),
      isPaid:         F('Payment made (independent of status)', 'bool', 'Phoenix', true, false, 'list tick'),
      paidDate:       F('Date payment was made', 'date', 'Phoenix', true, false, 'list tick')
    },

    exports: {
      exportRef:      F('Auto-generated outbound reference, e.g. EXP-2026-0001. Unique per entity.', 'string', 'Phoenix', true, false, 'list, detail, search'),
      entity:         F('Owning entity (Phoenix / Seychelles Breweries / Edena).', 'string', 'Phoenix', true, false, 'list scope, form'),
      tripType:       F('one_way (sample, return to supplier, scrap — no return) or round_trip (repair, refurbishment, calibration — item comes back).', 'string', 'Phoenix', true, false, 'form, lifecycle, metrics'),
      reason:         F('Reason for export: sample / return_to_supplier / repair / refurbishment / calibration / scrap / other.', 'string', 'Phoenix', true, false, 'form, metrics grouping'),
      mode:           F('Transport mode: AIR / SEA / COURIER.', 'string', 'Phoenix', true, false, 'form, list'),
      carrier:        F('Carrier / courier name (e.g. DHL, Emirates SkyCargo).', 'string', 'Phoenix', true, false, 'form, detail'),
      trackingRef:    F('Airway bill / courier tracking number / BL.', 'string', 'Phoenix', true, false, 'form, detail'),
      destination:    F('Where it is being sent — supplier / vendor / service provider name.', 'string', 'Phoenix', true, false, 'form, list'),
      destinationCountry: F('Destination country.', 'string', 'Phoenix', true, false, 'form, detail'),
      itemDescription: F('What is being exported (free text).', 'string', 'Phoenix', true, false, 'form, list, search'),
      quantity:       F('Quantity / number of items or packages.', 'string', 'Phoenix', true, false, 'form, detail'),
      linkedOrderId:  F('Optional linked ERP order/PO (orderId). Typically set for round_trip (the return generates/relates to a PO); optional for one_way.', 'string', 'Phoenix', true, false, 'form, detail, cross-link'),
      projectRef:     F('Optional free-text project reference when not tied to a PO.', 'string', 'Phoenix', true, false, 'form, detail'),
      status:         F('Lifecycle status (see REF.exportStatuses): Draft / Dispatched / In transit / Delivered / Return in transit / Received back / Closed / Cancelled.', 'string', 'Phoenix', true, false, 'list, detail, metrics'),
      dispatchDate:   F('Date the item was dispatched (outbound leg start). Anchor for turnaround.', 'date', 'Phoenix', true, false, 'form, metrics'),
      deliveredDate:  F('Date delivered to destination / vendor (outbound leg end).', 'date', 'Phoenix', true, false, 'form, metrics'),
      expectedReturnDate: F('For round_trip: expected date the item comes back. Overdue flagged if not received back by this date.', 'date', 'Phoenix', true, false, 'form, overdue flag'),
      returnDispatchDate: F('For round_trip: date the item was sent back to us by the vendor.', 'date', 'Phoenix', true, false, 'form'),
      receivedBackDate: F('For round_trip: date the item was received back (turnaround end).', 'date', 'Phoenix', true, false, 'form, metrics'),
      value:          F('Declared / insured value of the exported item.', 'number', 'Phoenix', true, false, 'form, detail'),
      currency:       F('Currency of the declared value.', 'string', 'Phoenix', true, false, 'form, detail'),
      logisticOfficer: F('Logistics officer responsible for this export.', 'string', 'Phoenix', true, false, 'form, list, My Work'),
      notes:          F('Free-text notes.', 'string', 'Phoenix', true, false, 'form, detail'),
      documentUrl:    F('SharePoint / OneDrive link to export docs (packing list, proforma, gate pass).', 'string', 'Phoenix', true, false, 'form, detail'),
      createdAt:      F('When the export record was created.', 'date', 'Phoenix', false, false, 'ordering'),
      createdBy:      F('Officer who created it.', 'string', 'Phoenix', false, false, 'audit'),
      updatedAt:      F('Last update timestamp.', 'date', 'Phoenix', false, false, 'concurrency'),
      updatedBy:      F('Officer who last updated it.', 'string', 'Phoenix', false, false, 'audit'),
      archived:       F('Soft-delete flag.', 'bool', 'Phoenix', false, false, 'hidden; backup')
    },

    suppliers: {
      entity:         F('Owning entity (Phoenix / Seychelles Breweries / Edena). Suppliers are per-entity: the same vendor name may exist separately under each entity with its own vendor code.', 'string', 'Phoenix', true, false, 'list scope, form'),
      name:           F('Supplier name', 'string', 'Phoenix', true, true, 'list, form'),
      legalName:      F('Supplier legal/registered name (used for ERP matching)', 'string', 'Phoenix', true, false, 'form, reconciliation'),
      country:        F('Country', 'string', 'Phoenix', true, false, 'list, form'),
      defaultCurrency:F('Default currency', 'string', 'Phoenix', true, false, 'form'),
      defaultTerms:   F('Default payment terms', 'string', 'Phoenix', true, false, 'form'),
      aliases:        F('Former/variant names (for reconciliation)', 'array', 'Phoenix', true, false, 'list, form'),
      erpMappings:    F('Per-entity ERP vendor mapping: array of {entity, erpSource, vendorNo, effectiveFrom, effectiveTo, active}; supports Navision-to-BC migration without losing history', 'array', 'Phoenix', true, false, 'form, import/reconciliation'),
      contacts:       F('Supplier contacts: array of {id, name, role, entity, purpose, escalationLevel, email, phone, preferred, active}', 'array', 'Phoenix', true, false, 'form, detail'),
      supplierRating: F('preferred / normal / watchlist / blocked', 'string', 'Phoenix', true, false, 'list, form'),
      supplierRatingReason: F('Reason supporting the current supplier rating, mandatory for watchlist and blocked', 'string', 'Phoenix', true, false, 'form, detail'),
      supplierRatingReviewDate: F('Next scheduled supplier rating review date', 'date', 'Phoenix', true, false, 'form, detail'),
      supplierRatingReviewedBy: F('Officer who last reviewed or changed the supplier rating', 'string', 'Phoenix', false, false, 'form audit, detail'),
      supplierRatingReviewedAt: F('Timestamp of the last supplier rating review or change', 'date', 'Phoenix', false, false, 'form audit, detail'),
      supplierRatingHistory: F('Append-only rating review history: array of {id, rating, reason, reviewDate, reviewedBy, reviewedAt, approvedBy}', 'array', 'Phoenix', false, false, 'detail'),
      mergedSupplierHistory: F('Audit history of supplier masters merged into this record: array of {sourceId, sourceName, mergedAt, mergedBy, reason}', 'array', 'Phoenix', false, false, 'detail'),
      mergedIntoSupplierId: F('For archived duplicate supplier records, the surviving supplier master id', 'string', 'Phoenix', false, false, 'archive audit'),
      mergedAt:       F('Timestamp when this duplicate supplier was merged', 'date', 'Phoenix', false, false, 'archive audit'),
      mergedBy:       F('Officer who performed the supplier merge', 'string', 'Phoenix', false, false, 'archive audit'),
      mergeReason:    F('Reason recorded for the supplier merge', 'string', 'Phoenix', false, false, 'archive audit'),
      active:         F('Active flag', 'bool', 'Phoenix', true, false, 'list, form'),
      notes:          F('Notes', 'string', 'Phoenix', true, false, 'form')
    },

    officers: {
      code:           F('2-letter officer code', 'string', 'Phoenix', true, true, 'everywhere (author/assignee)'),
      fullName:       F('Full name', 'string', 'Phoenix', true, true, 'lists, forms'),
      email:          F('Individual login email/username used to link the authenticated user to this officer profile', 'string', 'Phoenix', true, false, 'Officers & Roles, login mapping'),
      authUid:        F('Firebase Auth / SSO user id for direct officer-profile lookup', 'string', 'Phoenix', true, false, 'Officers & Roles, login mapping'),
      role:           F('admin or one of the current stream-specific roles: procurement_senior_manager, sc_manager, sc_supervisor, sc_officer, procurement_technical_manager, procurement_technical_supervisor, procurement_technical_officer, procurement_indirect_manager, procurement_indirect_supervisor, procurement_indirect_officer, logistics_manager, logistics_officer, demand_supervisor, demand_officer, finance, stakeholder', 'string', 'Phoenix', true, false, 'permissions'),
      function:       F('technical / indirect / supplychain', 'string', 'Phoenix', true, false, 'assignment'),
      active:         F('Active flag', 'bool', 'Phoenix', true, false, 'lists'),
      delegateToCode: F('Inc.5d: officer code to delegate My Work items to (set during absence)', 'string', 'Phoenix', true, false, 'delegation'),
      delegateUntil:  F('Inc.5d: delegation expiry date (inclusive); clears automatically after this date', 'date', 'Phoenix', true, false, 'delegation'),
      delegateReason: F('Inc.5d: reason / note for delegation (e.g. Annual leave)', 'string', 'Phoenix', true, false, 'delegation')
    },

    documents: {
      relatedType:    F('order / shipment / payment / supplier', 'string', 'Phoenix', false, true, 'section'),
      relatedId:      F('Parent record id', 'string', 'Phoenix', false, true, 'section'),
      documentType:   F('PO / Invoice / BL / COA / etc.', 'string', 'Phoenix', true, true, 'section, reports'),
      folder:         F('Folder: purchase_order / shipping_documents / payment_request / grn', 'string', 'Phoenix', true, false, 'order documents folders'),
      folderLabel:    F('Display label for the selected logical folder', 'string', 'Phoenix', false, false, 'documents, SharePoint-ready metadata'),
      poFolderName:   F('Future SharePoint parent folder: PO number plus supplier name', 'string', 'Phoenix', false, false, 'documents, SharePoint-ready metadata'),
      documentFolderPath: F('Human-readable logical folder path inside the PO folder', 'string', 'Phoenix', false, false, 'documents, reports'),
      sharePointFolderPath: F('SharePoint-ready folder path segments joined by /; actual folder creation is deferred to Graph integration', 'string', 'Phoenix', false, false, 'documents, future SharePoint upload'),
      storageProvider:F('metadata-only / sharepoint-link / demo-firestore', 'string', 'Phoenix', false, false, 'documents, reports'),
      documentName:   F('Display name', 'string', 'Phoenix', true, false, 'section'),
      documentUrl:    F('Link (SharePoint/OneDrive/path)', 'string', 'Phoenix', true, false, 'section'),
      fileData:       F('Demo: uploaded file as base64 data URL (small files; SharePoint link replaces this on implementation)', 'string', 'Phoenix', true, false, 'section upload'),
      fileName:       F('Uploaded file original name', 'string', 'Phoenix', true, false, 'section'),
      fileSize:       F('Uploaded file size (bytes)', 'number', 'Phoenix', true, false, 'section'),
      fileMime:       F('Uploaded file MIME type', 'string', 'Phoenix', true, false, 'section'),
      status:         F('missing / requested / received / approved / rejected', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      required:       F('Required/compliance document', 'bool', 'Phoenix', true, false, 'section, reports'),
      receivedDate:   F('Received date', 'date', 'Phoenix', true, false, 'section'),
      expiryDate:     F('Expiry date', 'date', 'Phoenix', true, false, 'section, alerts'),
      expiryAlertDays:F('Days-before-expiry to warn', 'number', 'Phoenix', true, false, 'section'),
      version:        F('Version/revision label', 'string', 'Phoenix', true, false, 'section'),
      verifiedBy:     F('Officer who verified', 'string', 'Phoenix', false, false, 'section'),
      verifiedAt:     F('Verification timestamp', 'date', 'Phoenix', false, false, 'section'),
      rejectedReason: F('Reason when status=rejected', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup'),
      archivedAt:     F('Archive timestamp', 'date', 'Phoenix', false, false, 'backup'),
      archivedBy:     F('Officer who archived', 'string', 'Phoenix', false, false, 'backup'),
      archiveReason:  F('Archive reason', 'string', 'Phoenix', false, false, 'backup')
    },

    followups: {
      relatedType:    F('Parent type', 'string', 'Phoenix', false, false, 'section'),
      relatedId:      F('Parent id', 'string', 'Phoenix', false, false, 'section'),
      comment:        F('Update/comment', 'string', 'Phoenix', true, false, 'section'),
      officer:        F('Author code', 'string', 'Phoenix', false, false, 'section'),
      nextAction:     F('Next action text', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      nextActionDueDate: F('Next action due date', 'date', 'Phoenix', true, false, 'section, reports, My Work'),
      assignedTo:     F('Assigned officer code', 'string', 'Phoenix', true, false, 'section, My Work'),
      status:         F('open / done / cancelled', 'string', 'Phoenix', true, false, 'section, reports'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup'),
      archivedAt:     F('Archive timestamp', 'date', 'Phoenix', false, false, 'backup'),
      archivedBy:     F('Officer who archived', 'string', 'Phoenix', false, false, 'backup'),
      archiveReason:  F('Archive reason', 'string', 'Phoenix', false, false, 'backup')
    },

    issues: {
      relatedType:    F('Parent type (standardized)', 'string', 'Phoenix', false, false, 'section, reports, My Work'),
      relatedId:      F('Parent id', 'string', 'Phoenix', false, false, 'section, reports, My Work'),
      issueType:      F('delay / missing document / customs / damage / shortage / etc.', 'string', 'Phoenix', true, false, 'section, reports'),
      issueCategory:  F('Cause / category code (root-cause classification)', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      severity:       F('low / medium / high / critical', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      impactType:     F('Operational impact: cost / time / quantity / compliance / quality', 'string', 'Phoenix', true, false, 'section, reports'),
      responsibleParty: F('supplier / freight forwarder / customs / internal / ERP-data', 'string', 'Phoenix', true, false, 'section, reports'),
      targetResolutionDate: F('Target resolution date (drives overdue alerts)', 'date', 'Phoenix', true, false, 'section, reports, My Work'),
      escalationLevel: F('Escalation level: 0 none / 1 supervisor / 2 manager / 3 head', 'number', 'Phoenix', true, false, 'section, reports, My Work'),
      escalatedTo:    F('Officer/role the issue is escalated to', 'string', 'Phoenix', true, false, 'section, My Work'),
      resolutionCode: F('Resolution outcome code', 'string', 'Phoenix', true, false, 'section, reports'),
      status:         F('open / resolved', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      owner:          F('Issue owner (officer code)', 'string', 'Phoenix', true, false, 'section, reports, My Work'),
      actionNotes:    F('What is being done', 'string', 'Phoenix', true, false, 'section, reports'),
      dataQualityKey: F('Stable source key for a Data Quality Cockpit work item; prevents duplicate linked actions for the same finding', 'string', 'Phoenix', false, false, 'Data Quality Cockpit, issue detail'),
      dataQualityMessage: F('Data Quality finding text captured when the linked action was created or reopened', 'string', 'Phoenix', false, false, 'Data Quality Cockpit, issue detail'),
      dataQualityLevel: F('Source Data Quality level: info / warn / danger', 'string', 'Phoenix', false, false, 'Data Quality Cockpit, issue detail'),
      openedBy:       F('Officer who opened', 'string', 'Phoenix', false, false, 'section'),
      openedDate:     F('Opened date', 'date', 'Phoenix', false, false, 'section, reports'),
      resolvedDate:   F('Resolved date', 'date', 'Phoenix', true, false, 'section'),
      resolvedBy:     F('Officer who resolved', 'string', 'Phoenix', false, false, 'section'),
      resolvedAt:     F('Resolution timestamp', 'date', 'Phoenix', false, false, 'section, reports'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup'),
      archivedAt:     F('Archive timestamp', 'date', 'Phoenix', false, false, 'backup'),
      archivedBy:     F('Officer who archived', 'string', 'Phoenix', false, false, 'backup'),
      archiveReason:  F('Archive reason', 'string', 'Phoenix', false, false, 'backup')
    },

    updateRequests: {
      entity:         F('Owning entity (follows the target order/shipment)', 'string', 'Phoenix', true, false, 'My Work, order/shipment detail'),
      targetType:     F('Target record type: order or shipment', 'string', 'Phoenix', true, false, 'My Work, order/shipment detail'),
      orderId:        F('Business PO number the request is about or linked to', 'string', 'Phoenix', true, false, 'My Work, order/shipment detail'),
      orderDocId:     F('Firestore id of the linked order, where available', 'string', 'Phoenix', true, false, 'open order detail'),
      shipmentId:     F('Business shipment reference when the request targets a shipment', 'string', 'Phoenix', false, false, 'My Work, shipment detail'),
      shipmentDocId:  F('Firestore id of the shipment when the request targets a shipment', 'string', 'Phoenix', false, false, 'open shipment detail'),
      supplier:       F('Supplier name (snapshot for display)', 'string', 'Phoenix', false, false, 'My Work card'),
      message:        F('What the stakeholder is asking for (free text)', 'string', 'Phoenix', true, false, 'My Work card, request detail'),
      requestorCode:  F('Officer/user code of the requesting stakeholder (current profile; real login when available)', 'string', 'Phoenix', false, false, 'My Work card'),
      requestorName:  F('Display name of the requestor (snapshot)', 'string', 'Phoenix', false, false, 'My Work card'),
      targetOfficers: F('Array of assigned officer codes notified (purchasing and/or logistics)', 'array', 'Phoenix', false, false, 'My Work routing'),
      status:         F('open / attended — open requests are persistent until an officer attends', 'string', 'Phoenix', true, false, 'My Work, order/shipment badges'),
      dueDate:        F('SLA due date (default request date + 3 working days) — drives on-time/overdue', 'date', 'Phoenix', false, false, 'My Work escalation'),
      createdAt:      F('When the request was raised', 'date', 'Phoenix', false, false, 'My Work card'),
      attendedBy:     F('Officer code who attended the request', 'string', 'Phoenix', false, false, 'request detail'),
      attendedAt:     F('When the request was attended', 'date', 'Phoenix', false, false, 'request detail'),
      attendNote:     F('Officer reply / what was done when attending', 'string', 'Phoenix', true, false, 'request detail'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup')
    },

    contactLog: {
      entity:         F('Owning entity (follows the order/shipment)', 'string', 'Phoenix', true, false, 'order/shipment detail, chase reports'),
      relatedType:    F('Linked record type: order or shipment', 'string', 'Phoenix', true, false, 'detail, chase reports'),
      orderId:        F('Business PO number this contact relates to', 'string', 'Phoenix', true, false, 'order detail timeline'),
      orderDocId:     F('Firestore id of the linked order, where available', 'string', 'Phoenix', false, false, 'open order detail'),
      shipmentId:     F('Business shipment reference when the contact targets a shipment', 'string', 'Phoenix', false, false, 'shipment detail timeline'),
      supplier:       F('Supplier name (snapshot for display)', 'string', 'Phoenix', false, false, 'detail, chase reports'),
      contactDate:    F('When the contact happened', 'date', 'Phoenix', true, false, 'timeline'),
      direction:      F('outbound (we contacted them) / inbound (they responded to us)', 'string', 'Phoenix', true, false, 'timeline'),
      channel:        F('Channel: email / phone / Teams / supplier portal / meeting / WhatsApp / other', 'string', 'Phoenix', true, false, 'timeline'),
      contactPerson:  F('Supplier-side person contacted / who responded (free text or from supplier contacts)', 'string', 'Phoenix', true, false, 'timeline'),
      summary:        F('What was said / asked / agreed (free text)', 'string', 'Phoenix', true, false, 'timeline'),
      responseExpectedBy: F('Date a reply / action is expected back from the supplier', 'date', 'Phoenix', true, false, 'timeline, auto-chase'),
      officerCode:    F('Officer who logged the contact (current profile)', 'string', 'Phoenix', false, false, 'timeline'),
      officerName:    F('Display name of the logging officer (snapshot)', 'string', 'Phoenix', false, false, 'timeline'),
      createdAt:      F('When the log entry was created', 'date', 'Phoenix', false, false, 'timeline ordering'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup')
    },

    kpiSnapshot: {
      entity:         F('Entity the snapshot belongs to', 'string', 'Phoenix', true, false, 'KPI trends'),
      period:         F('Period key YYYY-MM the snapshot represents', 'string', 'Phoenix', true, false, 'KPI trends, x-axis'),
      values:         F('Object of KPI values at capture: {otifPct,mtto,avgLateness,avgClearance,overduePayments,openOrders,highRisk,...}', 'object', 'Phoenix', true, false, 'KPI trend charts'),
      capturedAt:     F('When this snapshot was captured', 'date', 'Phoenix', false, false, 'KPI trends'),
      capturedBy:     F('Officer / system that captured it (auto = automatic monthly capture)', 'string', 'Phoenix', false, false, 'KPI trends'),
      source:         F('auto (first-load-of-month) / manual (recapture) / backfill (computed from historical dates)', 'string', 'Phoenix', false, false, 'KPI trends'),
      archived:       F('Soft-delete flag', 'bool', 'Phoenix', false, false, 'hidden; backup')
    },

    status_log: {
      entryType:      F('Record type (order/shipment/payment/...)', 'string', 'Phoenix', false, false, 'audit trail'),
      refId:          F('Record id this entry refers to', 'string', 'Phoenix', false, false, 'audit trail'),
      action:         F('created / updated / status-change / etc.', 'string', 'Phoenix', false, false, 'audit trail'),
      entryText:      F('Human description of the change', 'string', 'Phoenix', false, false, 'timeline'),
      officerCode:    F('Who made the change', 'string', 'Phoenix', false, false, 'timeline'),
      at:             F('Timestamp', 'date', 'Phoenix', false, false, 'timeline'),
      importRun:      F('Structured committed-Excel-import audit: {runId,status,source,fileName,fileSizeBytes,fileLastModified,sourceSheets,candidateCount,previewCreateCount,previewUpdateCount,entityCounts,functionCounts,sheetStats,skippedClosed,skippedUnmatched,validationErrorCount,conflictCount,unmatchedSupplierCount,groupedPOCount,activeRuleCount,storedRuleCount,created,updated,failed,processed,cancelled,rowErrors,completedAtClient}', 'map', 'Phoenix', false, false, 'ERP Reconciliation > Recent Import History')
    },

    system_config: {
      value:          F('Counter value (e.g. RFP sequence)', 'number', 'Phoenix', false, false, 'internal'),
      year:           F('Year of the counter', 'number', 'Phoenix', false, false, 'internal'),
      entity:         F('Entity the counter belongs to', 'string', 'Phoenix', false, false, 'internal'),
      configKey:      F('Named shared configuration key, e.g. erp_import_rules', 'string', 'Phoenix', false, false, 'internal, ERP Import Rules'),
      rules:           F('ERP Import Rules array: {ruleKey, ruleType, entity, erpSource, sourceField, matchValue, requiresBlankField, secondaryField, secondaryMatchValue, resultValue, priority, active, notes}', 'array', 'Phoenix', true, false, 'ERP Import Rules'),
      calendars:       F('Business calendars array: {entity, holidays:[{date: YYYY-MM-DD, label}]} used by working-day controls', 'array', 'Phoenix', true, false, 'Working Calendars, Data Quality, My Work')
    }
  };

  // Helpers
  function fields(coll) { return schema[coll] || {}; }
  function field(coll, key) { return (schema[coll] || {})[key] || null; }
  function requiredFields(coll) { return Object.keys(fields(coll)).filter(k => fields(coll)[k].required); }
  function ownerOf(coll, key) { const f = field(coll, key); return f ? f.owner : 'Phoenix'; }
  function collections() { return Object.keys(schema); }

  window.PXSchema = { schema, fields, field, requiredFields, ownerOf, collections };
})();
